import { useState } from "react";
import Head from "next/head";
import Footer from "../components/Footer";
import Tracks from "../components/Tracks";
import Navbar from "../components/Navbar";

export default function Home() {
  const [selectedHowl, setSelectedHowl] = useState(null);
  const [playing, setPlaying] = useState(false);

  return (
    <>
      <div>
        <Head>
          <title>Music Mazza</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar
          playing={playing}
          setPlaying={setPlaying}
          selectedHowl={selectedHowl}
        />
        <Tracks
          playing={playing}
          setPlaying={setPlaying}
          selectedHowl={selectedHowl}
          setSelectedHowl={setSelectedHowl}
        />
      </div>
      <Footer />
    </>
  );
}
